# Stage 1: Compile and Build angular codebase
FROM node:18.19.0 as build

# Set the working directory
WORKDIR /usr/local/app

# Add the source code to app
COPY ./ /usr/local/app/

# Install all the dependencies
RUN npm install

RUN npm install -g @angular/cli

# Generate the build of the application
#RUN npm run build
RUN ng build
RUN ls

# Stage 2: Serve app with nginx server

FROM nginx:latest


COPY nginx.conf /etc/nginx/nginx.conf
# Copy the build output to replace the default nginx contents.
#COPY dist/angular-conduit /usr/share/nginx/html
COPY --from=build /usr/local/app/dist/angular-conduit /usr/share/nginx/html
# Expose port 80
EXPOSE 80
